### ISSUE TITLE
[1.18.2] Persist album through death option is incompatible with Forgotten Graves

### ISSUE THREAD

**Issue by ConqAra** [Toma1O6/CollectorsAlbum#10]
[Forgotten Graves](https://www.curseforge.com/minecraft/mc-mods/forgotten-graves/) doesn't spawn a grave if this option is checked, weirdly enough. Looks like it just causes forgotten graves to break and not work at all if this mod forces an album to persist through death, even if you don't have an album in your inventory.

**Comment by Toma1O6** [comment]
In that case I suggest you to turn the option off again as there is not much I can do about it

**Comment by ConqAra** [comment]
alright, just checking if you had a solution first since the forgotten graves dev is busy, will put up an issue on their side rq tho

**Comment by Toma1O6** [comment]
I have managed to resolve the issues where these incompatibilities caused crashes, but looks like the mods are not fully compatible and I don't think its even possible currently.
As long as the game works and the issue can be worked around, I would keep it this way rather than breaking it again

**Comment by ginsm** [comment]
Howdy, I'm the dev for forgotten graves. I poked around and came up with a potential solution -- I created a package in your mod called `compat` and created a class inside said package which contains a set of strings: `GraveModIDs`. Next, inside the PlayerMixin, right before [L32](https://github.com/Toma1O6/CollectorsAlbum/blob/7db36c17f38343ad97d76adf41fc35fbd39d6cda/src/main/java/team/tnt/collectoralbum/mixins/PlayerMixin.java#L33) I ran the following code:

```java
for (String mod : ModCompat.GraveModIDs) {
    if (FabricLoader.getInstance().isModLoaded(mod)) return;
}
```

This works but it would be essentially handing over all drop/persistence behavior to the grave mod(s). This *could* cause confusion for the user because they'll see that persistence is enabled in your mod but the actual behavior would depend entirely on how the grave mod is configured. Perhaps a config setting related to allowing grave mods to handle persistence would reduce confusion in this case?

If that's not a solution you're fond of, I can simply make a wiki page on my end dedicated to mod compatibility and tell users to ensure that persistence is turned off in your mod if they'd like to use it with forgotten graves. Let me know what works best for you, or if you have a better idea, and lastly, happy holidays! :)

**Comment by Toma1O6** [comment]
Hi, thanks for the suggestion. At first I used `MixinPlugin` with list of mod IDs to manage the mixin loading, but I was not particularly fond of having to specify all grave mods. So I have tried adjusting the mixin itself (like replacing `@Redirect` with `@Inject`, but looks like that was not enough).
I'll propably revert the changes or just add disclaimer to curseforge to disable the config option, or even keep it disabled by default. I might also try to adjust the mixin further based on your mod, as I guess most grave mods will have similar implementation.
Thank you and have nice holidays too :)
